In [41]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import sklearn 
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import NearestNeighbors

In [6]:
# Importar o arquivo com os filmes e visualizar as primeiras linhas
filmes = pd.read_csv('https://criptodados.com.br/filmes/movies_metadata.csv', low_memory = False)
filmes.head(3)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0

In [7]:
# Importando o arquivo de avaliaÃ§Ãµes e avaliando as primeiras linhas
avaliacoes = pd.read_csv('https://criptodados.com.br/filmes/ratings.csv')
avaliacoes.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [8]:
# Filtrando somente as colunas necessÃ¡rios e renomeando nome das variaveis

# Seleciona somente as variaveis que iremos utilizar
filmes = filmes [['id','original_title','original_language','vote_count']]

In [9]:
# Renomeia as variaveis
filmes.rename(columns = {'id':'ID_FILME','original_title':'TITULO','original_language':'LINGUAGEM','vote_count':'QT_AVALIACOES'}, inplace = True)

In [10]:
# Exibe as primeiras linhas do arquivo tratado
filmes.head()

  ID_FILME                       TITULO LINGUAGEM  QT_AVALIACOES
0      862                    Toy Story        en         5415.0
1     8844                      Jumanji        en         2413.0
2    15602             Grumpier Old Men        en           92.0
3    31357            Waiting to Exhale        en           34.0
4    11862  Father of the Bride Part II        en          173.0

In [11]:
# Filtrando somente as colunas necessÃ¡rios e renomeando nome das variaveis

# Seleciona somente as variaveis que iremos utilizar
avaliacoes = avaliacoes [['userId','movieId','rating']]

In [12]:
# Renomeia as variaveis
avaliacoes.rename(columns = {'userId':'ID_USUARIO','movieId':'ID_FILME','rating':'AVALIACAO'}, inplace = True)

In [13]:
# Exibe as primeiras linhas do arquivo tratado
avaliacoes.head()

   ID_USUARIO  ID_FILME  AVALIACAO
0           1       110        1.0
1           1       147        4.5
2           1       858        5.0
3           1      1221        5.0
4           1      1246        5.0

In [14]:
# Verificando se hÃ¡ valores nulos
filmes.isna().sum()

ID_FILME          0
TITULO            0
LINGUAGEM        11
QT_AVALIACOES     6
dtype: int64

In [15]:
# Como sÃ£o poucos os valores nulos iremos remover porque nÃ£o terÃ¡ impacto nenhum
filmes.dropna(inplace = True)

In [16]:
# Verificando se hÃ¡ valores nulos novamente em filmes

# Verificando se hÃ¡ valores nulos
avaliacoes.isna().sum()

ID_USUARIO    0
ID_FILME      0
AVALIACAO     0
dtype: int64

In [17]:
# Verificando a quantidade de avaliacoes por usuarios
avaliacoes['ID_USUARIO'].value_counts()

ID_USUARIO
45811     18276
8659       9279
270123     7638
179792     7515
228291     7410
          ...
30155         1
9641          1
164717        1
243426        1
234625        1
Name: count, Length: 270896, dtype: int64

In [18]:
# Vamos pegar o ID_USUARIO somente de usuÃ¡rios que fizeram mais de 999 avaliaÃ§Ãµes
qt_avaliacoes = avaliacoes['ID_USUARIO'].value_counts() > 999
y = qt_avaliacoes[qt_avaliacoes].index
y.shape

(2509,)

In [19]:
# Visualizando os usuarios selecionados
y

Index([ 45811,   8659, 270123, 179792, 228291, 243443,  98415, 229879,  98787,
       172224,
       ...
       227649, 244253, 257117,  30733, 196384,  53075, 220764, 214328,  14354,
       182812],
      dtype='int64', name='ID_USUARIO', length=2509)

In [20]:
# visualizando o tamanho do dataset AvaliaÃ§Ãµes
avaliacoes.shape

(26024289, 3)

In [21]:
# Pegando somente avaliacoes dos usuarios que avaliaram mais de 999 vezes
avaliacoes = avaliacoes[avaliacoes['ID_USUARIO'].isin(y)]

In [22]:
# visualizando o tamanho do dataset AvaliaÃ§Ãµes
avaliacoes.shape

(3844582, 3)

In [23]:
# Visualizando o DataFrame Filmes
filmes.head()

  ID_FILME                       TITULO LINGUAGEM  QT_AVALIACOES
0      862                    Toy Story        en         5415.0
1     8844                      Jumanji        en         2413.0
2    15602             Grumpier Old Men        en           92.0
3    31357            Waiting to Exhale        en           34.0
4    11862  Father of the Bride Part II        en          173.0

In [24]:
# Vamos usar os filmes que possuem somente uma quantidade de avaliaÃ§Ãµes superior a 999 avaliaÃ§Ãµes
filmes = filmes[filmes['QT_AVALIACOES'] > 999]

In [25]:
# Vamos agrupar e visualizar a quantidade de filmes pela linguagem
filmes_linguagem = filmes['LINGUAGEM'].value_counts()
filmes_linguagem.head(20)

LINGUAGEM
en    1100
fr       5
ja       5
it       3
ko       2
pt       1
de       1
es       1
cn       1
sv       1
id       1
Name: count, dtype: int64

In [26]:
# Selecionar somente os filmes da linguagem EN (English)
filmes = filmes[filmes['LINGUAGEM'] == 'en']

In [29]:
# Visualizar os tipos de dados das variaveis
filmes.info()
avaliacoes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1100 entries, 0 to 44842
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_FILME       1100 non-null   object
 1   TITULO         1100 non-null   object
 2   LINGUAGEM      1100 non-null   object
 3   QT_AVALIACOES  1100 non-null   float64
dtypes: float64(1), object(3)
memory usage: 43.0+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 3844582 entries, 17291 to 26023521
Data columns (total 3 columns):
 #   Column      Dtype
---  ------      -----
 0   ID_USUARIO  int64
 1   ID_FILME    int64
 2   AVALIACAO   float64
dtypes: float64(1), int64(2)
memory usage: 117.3 MB

In [31]:
# Precisamos converter a variavel ID_FILME em inteiro
filmes['ID_FILME'] = filmes['ID_FILME'].astype(int)

# Concatenando os dataframes
avaliacoes_e_filmes = avaliacoes.merge(filmes, on = 'ID_FILME')
avaliacoes_e_filmes.head()

   ID_USUARIO  ID_FILME  AVALIACAO        TITULO LINGUAGEM  QT_AVALIACOES
0         229        12        1.0  Finding Nemo        en         6292.0
1         741        12        3.0  Finding Nemo        en         6292.0
2        1932        12        0.5  Finding Nemo        en         6292.0
3        3437        12        2.0  Finding Nemo        en         6292.0
4        3694        12        1.5  Finding Nemo        en         6292.0

In [32]:
# Verificando a quantidade de filmes com avaliacoes pelo tamanho do arquivo
avaliacoes_e_filmes.shape

(189882, 6)

In [33]:
# Verificando se hÃ¡ valores nulos
avaliacoes_e_filmes.isna().sum()

ID_USUARIO       0
ID_FILME         0
AVALIACAO        0
TITULO           0
LINGUAGEM        0
QT_AVALIACOES    0
dtype: int64

In [34]:
# Vamos visualizar as primeiras 20 linhas do arquivo
avaliacoes_e_filmes.head(20)

    ID_USUARIO  ID_FILME  AVALIACAO        TITULO LINGUAGEM  QT_AVALIACOES
0          229        12        1.0  Finding Nemo        en         6292.0
1          741        12        3.0  Finding Nemo        en         6292.0
2         1932        12        0.5  Finding Nemo        en         6292.0
3         3437        12        2.0  Finding Nemo        en         6292.0
4         3694        12        1.5  Finding Nemo        en         6292.0
5         3950        12        1.0  Finding Nemo        en         6292.0
6         4294        12        2.0  Finding Nemo        en         6292.0
7         4540        12        2.0  Finding Nemo        en         6292.0
8         4916        12        3.0  Finding Nemo        en         6292.0
9         4932        12        2.0  Finding Nemo        en         6292.0
10        5523        12        1.5  Finding Nemo        en         6292.0
11        5620        12        5.0  Finding Nemo        en         6292.0
12        5641        12        2.0  Finding Nemo        en         6292.0
13        5829        12        2.5  Finding Nemo        en         6292.0
14        6222        12        1.0  Finding Nemo        en         6292.0
15        6294        12        2.0  Finding Nemo        en         6292.0
16        6663        12        2.5  Finding Nemo        en         6292.0
17        6914        12        2.0  Finding Nemo        en         6292.0
18        7417        12        4.0  Finding Nemo        en         6292.0
19        7437        12        2.0  Finding Nemo        en         6292.0

In [36]:
# Agora precisamos fazer um PIVOT. O que queremos Ã© que cada ID_USUARIO seja uma variavel com o respectivo valor de nota
# para cada filme avaliado
filmes_pivot = avaliacoes_e_filmes.pivot_table(columns = 'ID_USUARIO', index = 'TITULO', values = 'AVALIACAO')

# Avaliar o arquivo transformado para PIVOT
filmes_pivot.head(20)

ID_USUARIO,229,231,741,836,1104,1136,1243,1380,1652,1846,...,269632,269750,269913,270071,270123,270213,270237,270564,270654,270887
TITULO,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.5,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN
12 Angry Men,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN
127 Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.5,2.0,NaN,NaN,NaN,NaN
2 Fast 2 Furious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001: A Space Odyssey,NaN,NaN,3.5,2.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,4.0,NaN,NaN,NaN,NaN,NaN
27 Dresses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28 Days Later,3.0,NaN,2.0,3.0,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,2.5,3.0,NaN,NaN,3.0,NaN
28 Weeks Later,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,4.0,1.0,...,NaN,0.5,3.0,1.0,2.0,3.0,NaN,2.5,NaN,NaN
300,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.5,4.0,3.0,3.0,1.5,NaN
3:10 to Yuma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4: Rise of the Silver Surfer,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.5,NaN,1.0,NaN,NaN,NaN,NaN
50 First Dates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
8 Mile,NaN,NaN,2.5,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,1.5,NaN,2.0,0.5,3.0,1.0,NaN,NaN,NaN
A Beautiful Mind,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Clockwork Orange,2.0,3.0,2.5,3.5,NaN,NaN,NaN,NaN,2.0,2.0,...,NaN,2.0,3.0,2.5,1.0,3.0,2.0,NaN,3.0,5.0
A Nightmare on Elm Street,3.0,2.5,3.0,1.5,4.0,3.0,5.0,3.0,4.0,4.0,...,4.0,3.0,3.0,3.5,3.0,4.0,3.0,2.5,3.0,5.0
A.I. Artificial Intelligence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AVP: Alien vs. Predator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ace Ventura: Pet Detective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN

In [37]:
# Os valores que sÃ£o nulos iremos preencher com ZERO
filmes_pivot.fillna(0, inplace = True)
filmes_pivot.head()

ID_USUARIO,229,231,741,836,1104,1136,1243,1380,1652,1846,...,269632,269750,269913,270071,270123,270213,270237,270564,270654,270887
TITULO,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.5,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0
12 Angry Men,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5,0.0
127 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1408,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.5,2.0,0.0,0.0,0.0,0.0
2 Fast 2 Furious,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
# Vamos importar o csr_matrix do pacote SciPy
# Esse mÃ©todo possibilita criarmos uma matriz sparsa
from scipy.sparse import csr_matrix

# Vamos transformar o nosso dataset em uma matriz sparsa
filmes_sparse = csr_matrix(filmes_pivot)

# Tipo do objeto
type(filmes_sparse)

# Vamos importar o algoritmo KNN do SciKit Learn
# from sklearn.neighbors import NearestNeighbors

# Criando e treinando o modelo preditivo
modelo = NearestNeighbors(algorithm = 'brute')
modelo.fit(filmes_sparse)

NearestNeighbors(algorithm='brute')

In [46]:
# Filtro utilizando como base "procurando o nemo - finding nemo"
distances, sugestions = modelo.kneighbors(filmes_pivot.filter(items = ['Finding Nemo'], axis=0).values.reshape(1, -1))

for i in range(len(sugestions)):
    print(filmes_pivot.index[sugestions[i]])

Index(['Finding Nemo', 'Shrek the Third', 'Kingdom of Heaven', 'Mars Attacks!',
       'Bridget Jones's Diary'],
      dtype='object', name='TITULO')